---
train:
  params:
    batch_size: 80
    epoch: 100
    lr: 0.0001
    decay: 1
    decay_step: 5000
    loss: Pinball
  save:
    save_path: "/home/cyh/GazeBenchmark/exp/Implementation/Gaze360-diapnoscale"
    model_name: Gaze360
    step: 10
  data:
    image: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/Image"
    label: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/ClusterLabel"
  pretrains: "None"
test:
   load:
      begin_step: 90
      end_step: 100
      steps: 10
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/Gaze360-diapnoscale"
      model_name: Gaze360
   data:
      image: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/Image"
      label: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/ClusterLabel"
reader: reader_diap
